<?php return array(
    'root' => array(
        'name' => 'laravel/laravel',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => '7521b38208d6486242943d0d3d7832c1e7df9ac4',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'asm89/stack-cors' => array(
            'pretty_version' => 'v2.0.3',
            'version' => '2.0.3.0',
            'reference' => '9cb795bf30988e8c96dd3c40623c48a877bc6714',
            'type' => 'library',
            'install_path' => __DIR__ . '/../asm89/stack-cors',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'aws/aws-crt-php' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'reference' => '3942776a8c99209908ee0b287746263725685732',
            'type' => 'library',
            'install_path' => __DIR__ . '/../aws/aws-crt-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'aws/aws-sdk-php' => array(
            'pretty_version' => '3.209.10',
            'version' => '3.209.10.0',
            'reference' => '45082e9fac26bdbc5db504639373374084f616d3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../aws/aws-sdk-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'barryvdh/laravel-dompdf' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'e3f429e97087b2ef19b83e5ed313f080f2477685',
            'type' => 'library',
            'install_path' => __DIR__ . '/../barryvdh/laravel-dompdf',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'barryvdh/laravel-ide-helper' => array(
            'pretty_version' => 'v2.10.0',
            'version' => '2.10.0.0',
            'reference' => '73b1012b927633a1b4cd623c2e6b1678e6faef08',
            'type' => 'library',
            'install_path' => __DIR__ . '/../barryvdh/laravel-ide-helper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'barryvdh/reflection-docblock' => array(
            'pretty_version' => 'v2.0.6',
            'version' => '2.0.6.0',
            'reference' => '6b69015d83d3daf9004a71a89f26e27d27ef6a16',
            'type' => 'library',
            'install_path' => __DIR__ . '/../barryvdh/reflection-docblock',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'beberlei/assert' => array(
            'pretty_version' => 'v3.3.2',
            'version' => '3.3.2.0',
            'reference' => 'cb70015c04be1baee6f5f5c953703347c0ac1655',
            'type' => 'library',
            'install_path' => __DIR__ . '/../beberlei/assert',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'brianium/paratest' => array(
            'pretty_version' => 'v6.3.0',
            'version' => '6.3.0.0',
            'reference' => '268d5b2b4237c0abf76c4aa9633ad8580be01e1e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../brianium/paratest',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'brick/math' => array(
            'pretty_version' => '0.9.2',
            'version' => '0.9.2.0',
            'reference' => 'dff976c2f3487d42c1db75a3b180e2b9f0e72ce0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../brick/math',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/ca-bundle' => array(
            'pretty_version' => '1.2.10',
            'version' => '1.2.10.0',
            'reference' => '9fdb22c2e97a614657716178093cd1da90a64aa8',
            'type' => 'library',
            'install_path' => __DIR__ . '/./ca-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/composer' => array(
            'pretty_version' => '2.1.3',
            'version' => '2.1.3.0',
            'reference' => 'fc5c4573aafce3a018eb7f1f8f91cea423970f2e',
            'type' => 'library',
            'install_path' => __DIR__ . '/./composer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/metadata-minifier' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'c549d23829536f0d0e984aaabbf02af91f443207',
            'type' => 'library',
            'install_path' => __DIR__ . '/./metadata-minifier',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/package-versions-deprecated' => array(
            'pretty_version' => '1.11.99.2',
            'version' => '1.11.99.2',
            'reference' => 'c6522afe5540d5fc46675043d3ed5a45a740b27c',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/./package-versions-deprecated',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/pcre' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '67a32d7d6f9f560b726ab25a061b38ff3a80c560',
            'type' => 'library',
            'install_path' => __DIR__ . '/./pcre',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/semver' => array(
            'pretty_version' => '3.3.2',
            'version' => '3.3.2.0',
            'reference' => '3953f23262f2bff1919fc82183ad9acb13ff62c9',
            'type' => 'library',
            'install_path' => __DIR__ . '/./semver',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/spdx-licenses' => array(
            'pretty_version' => '1.5.5',
            'version' => '1.5.5.0',
            'reference' => 'de30328a7af8680efdc03e396aad24befd513200',
            'type' => 'library',
            'install_path' => __DIR__ . '/./spdx-licenses',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/xdebug-handler' => array(
            'pretty_version' => '2.0.5',
            'version' => '2.0.5.0',
            'reference' => '9e36aeed4616366d2b690bdce11f71e9178c579a',
            'type' => 'library',
            'install_path' => __DIR__ . '/./xdebug-handler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'cordoval/hamcrest-php' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'davedevelopment/hamcrest-php' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'dealerdirect/phpcodesniffer-composer-installer' => array(
            'pretty_version' => 'v0.7.2',
            'version' => '0.7.2.0',
            'reference' => '1c968e542d8843d7cd71de3c5c9c3ff3ad71a1db',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../dealerdirect/phpcodesniffer-composer-installer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'defuse/php-encryption' => array(
            'pretty_version' => 'v2.3.1',
            'version' => '2.3.1.0',
            'reference' => '77880488b9954b7884c25555c2a0ea9e7053f9d2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../defuse/php-encryption',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/annotations' => array(
            'pretty_version' => '1.13.3',
            'version' => '1.13.3.0',
            'reference' => '648b0343343565c4a056bfc8392201385e8d89f0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/annotations',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'doctrine/cache' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'reference' => 'c9622c6820d3ede1e2315a6a377ea1076e421d88',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/dbal' => array(
            'pretty_version' => '3.1.1',
            'version' => '3.1.1.0',
            'reference' => '8e0fde2b90e3f61361013d1e928621beeea07bc0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/dbal',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/deprecations' => array(
            'pretty_version' => 'v0.5.3',
            'version' => '0.5.3.0',
            'reference' => '9504165960a1f83cc1480e2be1dd0a0478561314',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/deprecations',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/event-manager' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'reference' => '41370af6a30faa9dc0368c4a6814d596e81aba7f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/event-manager',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/inflector' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'reference' => '9cf661f4eb38f7c881cac67c75ea9b00bf97b210',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/inflector',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/instantiator' => array(
            'pretty_version' => '1.4.1',
            'version' => '1.4.1.0',
            'reference' => '10dcfce151b967d20fde1b34ae6640712c3891bc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/instantiator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'doctrine/lexer' => array(
            'pretty_version' => '1.2.3',
            'version' => '1.2.3.0',
            'reference' => 'c268e882d4dbdd85e36e4ad69e02dc284f89d229',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/lexer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dompdf/dompdf' => array(
            'pretty_version' => 'v1.1.1',
            'version' => '1.1.1.0',
            'reference' => 'de4aad040737a89fae2129cdeb0f79c45513128d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dompdf/dompdf',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dragonmantank/cron-expression' => array(
            'pretty_version' => 'v3.1.0',
            'version' => '3.1.0.0',
            'reference' => '7a8c6e56ab3ffcc538d05e8155bb42269abf1a0c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dragonmantank/cron-expression',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'egulias/email-validator' => array(
            'pretty_version' => '2.1.25',
            'version' => '2.1.25.0',
            'reference' => '0dbf5d78455d4d6a41d186da50adc1122ec066f4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../egulias/email-validator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'evenement/evenement' => array(
            'pretty_version' => 'v3.0.1',
            'version' => '3.0.1.0',
            'reference' => '531bfb9d15f8aa57454f5f0285b18bec903b8fb7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../evenement/evenement',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ezyang/htmlpurifier' => array(
            'pretty_version' => 'v4.14.0',
            'version' => '4.14.0.0',
            'reference' => '12ab42bd6e742c70c0a52f7b82477fcd44e64b75',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezyang/htmlpurifier',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'facade/flare-client-php' => array(
            'pretty_version' => '1.8.1',
            'version' => '1.8.1.0',
            'reference' => '47b639dc02bcfdfc4ebb83de703856fa01e35f5f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../facade/flare-client-php',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'facade/ignition' => array(
            'pretty_version' => '2.10.2',
            'version' => '2.10.2.0',
            'reference' => '43688227bbf27c43bc1ad83af224f135b6ef0ff4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../facade/ignition',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'facade/ignition-contracts' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => '3c921a1cdba35b68a7f0ccffc6dffc1995b18267',
            'type' => 'library',
            'install_path' => __DIR__ . '/../facade/ignition-contracts',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'fakerphp/faker' => array(
            'pretty_version' => 'v1.15.0',
            'version' => '1.15.0.0',
            'reference' => '89c6201c74db25fa759ff16e78a4d8f32547770e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fakerphp/faker',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'fideloper/proxy' => array(
            'pretty_version' => '4.4.1',
            'version' => '4.4.1.0',
            'reference' => 'c073b2bd04d1c90e04dc1b787662b558dd65ade0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fideloper/proxy',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'filp/whoops' => array(
            'pretty_version' => '2.13.0',
            'version' => '2.13.0.0',
            'reference' => '2edbc73a4687d9085c8f20f398eebade844e8424',
            'type' => 'library',
            'install_path' => __DIR__ . '/../filp/whoops',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'firebase/php-jwt' => array(
            'pretty_version' => 'v5.4.0',
            'version' => '5.4.0.0',
            'reference' => 'd2113d9b2e0e349796e72d2a63cf9319100382d2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../firebase/php-jwt',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'flix-tech/avro-php' => array(
            'pretty_version' => '4.2.0',
            'version' => '4.2.0.0',
            'reference' => 'd56613999a042c26dad8d5f2d53012cd3db4b8f7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../flix-tech/avro-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'flix-tech/avro-serde-php' => array(
            'pretty_version' => '1.7.1',
            'version' => '1.7.1.0',
            'reference' => 'fabd439f31b0d0fbd0f9bb70c13ad04efd16cd83',
            'type' => 'library',
            'install_path' => __DIR__ . '/../flix-tech/avro-serde-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'flix-tech/confluent-schema-registry-api' => array(
            'pretty_version' => '7.5.1',
            'version' => '7.5.1.0',
            'reference' => '300bf29d61ed50e91a11ef12aa51dd53800aab6e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../flix-tech/confluent-schema-registry-api',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'friendsofphp/php-cs-fixer' => array(
            'pretty_version' => 'v3.4.0',
            'version' => '3.4.0.0',
            'reference' => '47177af1cfb9dab5d1cc4daf91b7179c2efe7fad',
            'type' => 'application',
            'install_path' => __DIR__ . '/../friendsofphp/php-cs-fixer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'fruitcake/laravel-cors' => array(
            'pretty_version' => 'v2.0.4',
            'version' => '2.0.4.0',
            'reference' => 'a8ccedc7ca95189ead0e407c43b530dc17791d6a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fruitcake/laravel-cors',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'functional-php/fantasy-land' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '1e2366e68057bbc7a65d58dd663324eb9b299775',
            'type' => 'library',
            'install_path' => __DIR__ . '/../functional-php/fantasy-land',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'graham-campbell/result-type' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'reference' => '7e279d2cd5d7fbb156ce46daada972355cea27bb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../graham-campbell/result-type',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'grogy/php-parallel-lint' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '7.4.1',
            'version' => '7.4.1.0',
            'reference' => 'ee0a041b1760e6a53d2a39c8c34115adc2af2c79',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '1.5.1',
            'version' => '1.5.1.0',
            'reference' => 'fe752aedc9fd8fcca3fe7ad05d419d32998a06da',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '1.8.3',
            'version' => '1.8.3.0',
            'reference' => '1afdd860a2566ed3c2b0b4a3de6e23434a79ec85',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'hamcrest/hamcrest-php' => array(
            'pretty_version' => 'v2.0.1',
            'version' => '2.0.1.0',
            'reference' => '8c3d0a3f6af734494ad8f6fbbee0ba92422859f3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../hamcrest/hamcrest-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/auth' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/broadcasting' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/bus' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/cache' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/collections' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/config' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/console' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/container' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/contracts' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/cookie' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/database' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/encryption' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/events' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/filesystem' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/hashing' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/http' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/log' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/macroable' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/mail' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/notifications' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/pagination' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/pipeline' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/queue' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/redis' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/routing' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/session' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/support' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/testing' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/translation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/validation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/view' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'itsgoingd/clockwork' => array(
            'pretty_version' => 'v5.1.8',
            'version' => '5.1.8.0',
            'reference' => '74ee05a61296aa7298164ef5346f0a568aa6106e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../itsgoingd/clockwork',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jakub-onderka/php-parallel-lint' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'jean85/pretty-package-versions' => array(
            'pretty_version' => '1.6.0',
            'version' => '1.6.0.0',
            'reference' => '1e0104b46f045868f11942aea058cd7186d6c303',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jean85/pretty-package-versions',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jenssegers/mongodb' => array(
            'pretty_version' => '3.8.4',
            'version' => '3.8.4.0',
            'reference' => '6aa6ad12b3b52eeab1d090f282c14123ffad1dc9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jenssegers/mongodb',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'justinrainbow/json-schema' => array(
            'pretty_version' => '5.2.12',
            'version' => '5.2.12.0',
            'reference' => 'ad87d5a5ca981228e0e205c2bc7dfb8e24559b60',
            'type' => 'library',
            'install_path' => __DIR__ . '/../justinrainbow/json-schema',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kodova/hamcrest-php' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'laravel/framework' => array(
            'pretty_version' => 'v8.49.2',
            'version' => '8.49.2.0',
            'reference' => 'd9b43ee080b4d51344b2e578aa667f85040471a2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel/framework',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laravel/horizon' => array(
            'pretty_version' => 'v5.7.9',
            'version' => '5.7.9.0',
            'reference' => '50dc53b105ec612cf1a87e89fffd21cc0a43003c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel/horizon',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laravel/laravel' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '7521b38208d6486242943d0d3d7832c1e7df9ac4',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laravel/passport' => array(
            'pretty_version' => 'v10.1.3',
            'version' => '10.1.3.0',
            'reference' => 'a5e4471dd99b7638ab5ca3ecab6cd87cf37eb410',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel/passport',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laravel/slack-notification-channel' => array(
            'pretty_version' => 'v2.4.0',
            'version' => '2.4.0.0',
            'reference' => '060617a31562c88656c95c5971a36989122d4b53',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel/slack-notification-channel',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laravel/telescope' => array(
            'pretty_version' => 'v4.5.1',
            'version' => '4.5.1.0',
            'reference' => '77373b6dccfc0c4372f1a09c9064cbe7b6d1bf76',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel/telescope',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laravel/tinker' => array(
            'pretty_version' => 'v2.6.1',
            'version' => '2.6.1.0',
            'reference' => '04ad32c1a3328081097a181875733fa51f402083',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel/tinker',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laravel/ui' => array(
            'pretty_version' => 'v3.3.0',
            'version' => '3.3.0.0',
            'reference' => '07d725813350c695c779382cbd6dac0ab8665537',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel/ui',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'lcobucci/clock' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => '353d83fe2e6ae95745b16b3d911813df6a05bfb3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../lcobucci/clock',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'lcobucci/jwt' => array(
            'pretty_version' => '4.1.4',
            'version' => '4.1.4.0',
            'reference' => '71cf170102c8371ccd933fa4df6252086d144de6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../lcobucci/jwt',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/commonmark' => array(
            'pretty_version' => '1.6.5',
            'version' => '1.6.5.0',
            'reference' => '44ffd8d3c4a9133e4bd0548622b09c55af39db5f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/commonmark',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/container' => array(
            'pretty_version' => '4.2.0',
            'version' => '4.2.0.0',
            'reference' => '375d13cb828649599ef5d48a339c4af7a26cd0ab',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/container',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'league/event' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'reference' => 'd2cc124cf9a3fab2bb4ff963307f60361ce4d119',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/event',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/flysystem' => array(
            'pretty_version' => '1.1.9',
            'version' => '1.1.9.0',
            'reference' => '094defdb4a7001845300334e7c1ee2335925ef99',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/flysystem',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/flysystem-aws-s3-v3' => array(
            'pretty_version' => '1.0.29',
            'version' => '1.0.29.0',
            'reference' => '4e25cc0582a36a786c31115e419c6e40498f6972',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/flysystem-aws-s3-v3',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/mime-type-detection' => array(
            'pretty_version' => '1.9.0',
            'version' => '1.9.0.0',
            'reference' => 'aa70e813a6ad3d1558fc927863d47309b4c23e69',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/mime-type-detection',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/oauth2-server' => array(
            'pretty_version' => '8.2.4',
            'version' => '8.2.4.0',
            'reference' => '622eaa1f28eb4a2dea0cfc7e4f5280fac794e83c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/oauth2-server',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/oauth2server' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'lncd/oauth2' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'maennchen/zipstream-php' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'reference' => 'c4c5803cc1f93df3d2448478ef79394a5981cc58',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maennchen/zipstream-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'markbaker/complex' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'reference' => 'ab8bc271e404909db09ff2d5ffa1e538085c0f22',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/complex',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'markbaker/matrix' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'c66aefcafb4f6c269510e9ac46b82619a904c576',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/matrix',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mateusjunges/laravel-kafka' => array(
            'pretty_version' => 'v1.7.0',
            'version' => '1.7.0.0',
            'reference' => '504b27509e79c141974a8b99c20003885a6dbc7d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mateusjunges/laravel-kafka',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mockery/mockery' => array(
            'pretty_version' => '1.4.3',
            'version' => '1.4.3.0',
            'reference' => 'd1339f64479af1bee0e82a0413813fe5345a54ea',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mockery/mockery',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mongodb/mongodb' => array(
            'pretty_version' => '1.8.0',
            'version' => '1.8.0.0',
            'reference' => '953dbc19443aa9314c44b7217a16873347e6840d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mongodb/mongodb',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'monolog/monolog' => array(
            'pretty_version' => '2.3.0',
            'version' => '2.3.0.0',
            'reference' => 'df991fd88693ab703aa403413d83e15f688dae33',
            'type' => 'library',
            'install_path' => __DIR__ . '/../monolog/monolog',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mtdowling/cron-expression' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '^1.0',
            ),
        ),
        'mtdowling/jmespath.php' => array(
            'pretty_version' => '2.6.1',
            'version' => '2.6.1.0',
            'reference' => '9b87907a81b87bc76d19a7fb2d61e61486ee9edb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mtdowling/jmespath.php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'myclabs/deep-copy' => array(
            'pretty_version' => '1.11.0',
            'version' => '1.11.0.0',
            'reference' => '14daed4296fae74d9e3201d2c4925d1acb7aa614',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/deep-copy',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'myclabs/php-enum' => array(
            'pretty_version' => '1.8.3',
            'version' => '1.8.3.0',
            'reference' => 'b942d263c641ddb5190929ff840c68f78713e937',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/php-enum',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nesbot/carbon' => array(
            'pretty_version' => '2.50.0',
            'version' => '2.50.0.0',
            'reference' => 'f47f17d17602b2243414a44ad53d9f8b9ada5fdb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nesbot/carbon',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nikic/php-parser' => array(
            'pretty_version' => 'v4.15.1',
            'version' => '4.15.1.0',
            'reference' => '0ef6c55a3f47f89d7a374e6f835197a0b5fcf900',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nunomaduro/collision' => array(
            'pretty_version' => 'v5.5.0',
            'version' => '5.5.0.0',
            'reference' => 'b5cb36122f1c142c3c3ee20a0ae778439ef0244b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nunomaduro/collision',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'nunomaduro/phpinsights' => array(
            'pretty_version' => 'v2.6.1',
            'version' => '2.6.1.0',
            'reference' => '0743eb75ded697d71747725c9cfcce6fa89fb003',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nunomaduro/phpinsights',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'nyholm/psr7' => array(
            'pretty_version' => '1.4.1',
            'version' => '1.4.1.0',
            'reference' => '2212385b47153ea71b1c1b1374f8cb5e4f7892ec',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nyholm/psr7',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ocramius/package-versions' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.11.99',
            ),
        ),
        'opis/closure' => array(
            'pretty_version' => '3.6.2',
            'version' => '3.6.2.0',
            'reference' => '06e2ebd25f2869e54a306dda991f7db58066f7f6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../opis/closure',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'orno/di' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '~2.0',
            ),
        ),
        'paragonie/constant_time_encoding' => array(
            'pretty_version' => 'v2.4.0',
            'version' => '2.4.0.0',
            'reference' => 'f34c2b11eb9d2c9318e13540a1dbc2a3afbd939c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/constant_time_encoding',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'paragonie/random_compat' => array(
            'pretty_version' => 'v9.99.100',
            'version' => '9.99.100.0',
            'reference' => '996434e5492cb4c3edcb9168db6fbb1359ef965a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/random_compat',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phar-io/manifest' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'reference' => '97803eca37d319dfa7826cc2437fc020857acb53',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/manifest',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phar-io/version' => array(
            'pretty_version' => '3.2.1',
            'version' => '3.2.1.0',
            'reference' => '4f7fd7836c6f332bb2933569e566a0d6c4cbed74',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/version',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phenx/php-font-lib' => array(
            'pretty_version' => '0.5.2',
            'version' => '0.5.2.0',
            'reference' => 'ca6ad461f032145fff5971b5985e5af9e7fa88d8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phenx/php-font-lib',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phenx/php-svg-lib' => array(
            'pretty_version' => '0.3.4',
            'version' => '0.3.4.0',
            'reference' => 'f627771eb854aa7f45f80add0f23c6c4d67ea0f2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phenx/php-svg-lib',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-cs-fixer/diff' => array(
            'pretty_version' => 'v2.0.2',
            'version' => '2.0.2.0',
            'reference' => '29dc0d507e838c4580d018bd8b5cb412474f7ec3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-cs-fixer/diff',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'php-http/async-client-implementation' => array(
            'dev_requirement' => true,
            'provided' => array(
                0 => '*',
            ),
        ),
        'php-http/client-implementation' => array(
            'dev_requirement' => true,
            'provided' => array(
                0 => '*',
            ),
        ),
        'php-http/message-factory' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'reference' => 'a478cb11f66a6ac48d8954216cfed9aa06a501a1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/message-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-parallel-lint/php-parallel-lint' => array(
            'pretty_version' => 'v1.3.2',
            'version' => '1.3.2.0',
            'reference' => '6483c9832e71973ed29cf71bd6b3f4fde438a9de',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-parallel-lint/php-parallel-lint',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpdocumentor/reflection-common' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'reference' => '1d01c49d4ed62f25aa84a747ad35d5a16924662b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-common',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpdocumentor/type-resolver' => array(
            'pretty_version' => '1.6.1',
            'version' => '1.6.1.0',
            'reference' => '77a32518733312af16a44300404e945338981de3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/type-resolver',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phploc/phploc' => array(
            'pretty_version' => '7.0.2',
            'version' => '7.0.2.0',
            'reference' => 'af0d5fc84f3f7725513ba59cdcbe670ac2a4532a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phploc/phploc',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpoffice/phpspreadsheet' => array(
            'pretty_version' => '1.23.0',
            'version' => '1.23.0.0',
            'reference' => '21e4cf62699eebf007db28775f7d1554e612ed9e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoffice/phpspreadsheet',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpoption/phpoption' => array(
            'pretty_version' => '1.7.5',
            'version' => '1.7.5.0',
            'reference' => '994ecccd8f3283ecf5ac33254543eb0ac946d525',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoption/phpoption',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpseclib/phpseclib' => array(
            'pretty_version' => '3.0.9',
            'version' => '3.0.9.0',
            'reference' => 'a127a5133804ff2f47ae629dd529b129da616ad7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpseclib/phpseclib',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpstan/phpdoc-parser' => array(
            'pretty_version' => '1.8.0',
            'version' => '1.8.0.0',
            'reference' => '8dd908dd6156e974b9a0f8bb4cd5ad0707830f04',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpstan/phpdoc-parser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-code-coverage' => array(
            'pretty_version' => '9.2.17',
            'version' => '9.2.17.0',
            'reference' => 'aa94dc41e8661fe90c7316849907cba3007b10d8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-code-coverage',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-file-iterator' => array(
            'pretty_version' => '3.0.6',
            'version' => '3.0.6.0',
            'reference' => 'cf1c2e7c203ac650e352f4cc675a7021e7d1b3cf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-file-iterator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-invoker' => array(
            'pretty_version' => '3.1.1',
            'version' => '3.1.1.0',
            'reference' => '5a10147d0aaf65b58940a0b72f71c9ac0423cc67',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-invoker',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-text-template' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'reference' => '5da5f67fc95621df9ff4c4e5a84d6a8a2acf7c28',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-text-template',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-timer' => array(
            'pretty_version' => '5.0.3',
            'version' => '5.0.3.0',
            'reference' => '5a63ce20ed1b5bf577850e2c4e87f4aa902afbd2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-timer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/phpunit' => array(
            'pretty_version' => '9.5.24',
            'version' => '9.5.24.0',
            'reference' => 'd0aa6097bef9fd42458a9b3c49da32c6ce6129c5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'predis/predis' => array(
            'pretty_version' => 'v1.1.7',
            'version' => '1.1.7.0',
            'reference' => 'b240daa106d4e02f0c5b7079b41e31ddf66fddf8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../predis/predis',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/cache' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => '213f9dbc5b9bfbc4f8db86d2838dc968752ce13b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/cache',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'psr/cache-implementation' => array(
            'dev_requirement' => true,
            'provided' => array(
                0 => '1.0|2.0',
            ),
        ),
        'psr/container' => array(
            'pretty_version' => '1.1.2',
            'version' => '1.1.2.0',
            'reference' => '513e0666f7216c7459170d56df27dfcefe1689ea',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
                1 => '^1.0',
            ),
        ),
        'psr/event-dispatcher' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'dbefd12671e8a14ec7f180cab83036ed26714bb0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '2dfb5f6c5eff0e91e20e913f8c5452ed95b86621',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '12ac7fcd07e5b077433f5f2bee95b3a771bf61be',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'f6561bf28d520154e4b0ec72be95418abe6d9363',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0.0',
                1 => '1.0|2.0',
                2 => '1.0',
            ),
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/simple-cache-implementation' => array(
            'dev_requirement' => true,
            'provided' => array(
                0 => '1.0|2.0',
            ),
        ),
        'psy/psysh' => array(
            'pretty_version' => 'v0.10.8',
            'version' => '0.10.8.0',
            'reference' => 'e4573f47750dd6c92dca5aee543fa77513cbd8d3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psy/psysh',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ramsey/collection' => array(
            'pretty_version' => '1.1.3',
            'version' => '1.1.3.0',
            'reference' => '28a5c4ab2f5111db6a60b2b4ec84057e0f43b9c1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ramsey/collection',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ramsey/uuid' => array(
            'pretty_version' => '4.1.1',
            'version' => '4.1.1.0',
            'reference' => 'cd4032040a750077205918c86049aa0f43d22947',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ramsey/uuid',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'react/cache' => array(
            'pretty_version' => 'v1.1.1',
            'version' => '1.1.1.0',
            'reference' => '4bf736a2cccec7298bdf745db77585966fc2ca7e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'react/dns' => array(
            'pretty_version' => 'v1.7.0',
            'version' => '1.7.0.0',
            'reference' => 'a45784faebf8fbd59058fad2d8497f71a787d20c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/dns',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'react/event-loop' => array(
            'pretty_version' => 'v1.1.1',
            'version' => '1.1.1.0',
            'reference' => '6d24de090cd59cfc830263cfba965be77b563c13',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/event-loop',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'react/http' => array(
            'pretty_version' => 'v1.2.0',
            'version' => '1.2.0.0',
            'reference' => 'badb0a87890e14b9cdfa3aec3ba1aafd900401ac',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/http',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'react/promise' => array(
            'pretty_version' => 'v2.8.0',
            'version' => '2.8.0.0',
            'reference' => 'f3cff96a19736714524ca0dd1d4130de73dbbbc4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/promise',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'react/promise-stream' => array(
            'pretty_version' => 'v1.2.0',
            'version' => '1.2.0.0',
            'reference' => '6384d8b76cf7dcc44b0bf3343fb2b2928412d1fe',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/promise-stream',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'react/promise-timer' => array(
            'pretty_version' => 'v1.6.0',
            'version' => '1.6.0.0',
            'reference' => 'daee9baf6ef30c43ea4c86399f828bb5f558f6e6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/promise-timer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'react/socket' => array(
            'pretty_version' => 'v1.7.0',
            'version' => '1.7.0.0',
            'reference' => '5d39e3fa56ea7cc443c86f2788a40867cdba1659',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/socket',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'react/stream' => array(
            'pretty_version' => 'v1.1.1',
            'version' => '1.1.1.0',
            'reference' => '7c02b510ee3f582c810aeccd3a197b9c2f52ff1a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/stream',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'rhumsaa/uuid' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.1.1',
            ),
        ),
        'ringcentral/psr7' => array(
            'pretty_version' => '1.3.0',
            'version' => '1.3.0.0',
            'reference' => '360faaec4b563958b673fb52bbe94e37f14bc686',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ringcentral/psr7',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sabberworm/php-css-parser' => array(
            'pretty_version' => '8.3.1',
            'version' => '8.3.1.0',
            'reference' => 'd217848e1396ef962fb1997cf3e2421acba7f796',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sabberworm/php-css-parser',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sebastian/cli-parser' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '442e7c7e687e42adc03470c7b668bc4b2402c0b2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/cli-parser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/code-unit' => array(
            'pretty_version' => '1.0.8',
            'version' => '1.0.8.0',
            'reference' => '1fc9f64c0927627ef78ba436c9b17d967e68e120',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/code-unit-reverse-lookup' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'reference' => 'ac91f01ccec49fb77bdc6fd1e548bc70f7faa3e5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit-reverse-lookup',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/comparator' => array(
            'pretty_version' => '4.0.8',
            'version' => '4.0.8.0',
            'reference' => 'fa0f136dd2334583309d32b62544682ee972b51a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/comparator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/complexity' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => '739b35e53379900cc9ac327b2147867b8b6efd88',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/complexity',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/diff' => array(
            'pretty_version' => '4.0.4',
            'version' => '4.0.4.0',
            'reference' => '3461e3fccc7cfdfc2720be910d3bd73c69be590d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/diff',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/environment' => array(
            'pretty_version' => '5.1.4',
            'version' => '5.1.4.0',
            'reference' => '1b5dff7bb151a4db11d49d90e5408e4e938270f7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/environment',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/exporter' => array(
            'pretty_version' => '4.0.5',
            'version' => '4.0.5.0',
            'reference' => 'ac230ed27f0f98f597c8a2b6eb7ac563af5e5b9d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/exporter',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/global-state' => array(
            'pretty_version' => '5.0.5',
            'version' => '5.0.5.0',
            'reference' => '0ca8db5a5fc9c8646244e629625ac486fa286bf2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/global-state',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/lines-of-code' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'reference' => 'c1c2e997aa3146983ed888ad08b15470a2e22ecc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/lines-of-code',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/object-enumerator' => array(
            'pretty_version' => '4.0.4',
            'version' => '4.0.4.0',
            'reference' => '5c9eeac41b290a3712d88851518825ad78f45c71',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-enumerator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/object-reflector' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'reference' => 'b4f479ebdbf63ac605d183ece17d8d7fe49c15c7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-reflector',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/recursion-context' => array(
            'pretty_version' => '4.0.4',
            'version' => '4.0.4.0',
            'reference' => 'cd9d8cf3c5804de4341c283ed787f099f5506172',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/recursion-context',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/resource-operations' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '0f4443cb3a1d92ce809899753bc0d5d5a8dd19a8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/resource-operations',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/type' => array(
            'pretty_version' => '3.2.0',
            'version' => '3.2.0.0',
            'reference' => 'fb3fe09c5f0bae6bc27ef3ce933a1e0ed9464b6e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/type',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/version' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => 'c6c1022351a901512170118436c764e473f6de8c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/version',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'seld/jsonlint' => array(
            'pretty_version' => '1.8.3',
            'version' => '1.8.3.0',
            'reference' => '9ad6ce79c342fbd44df10ea95511a1b24dee5b57',
            'type' => 'library',
            'install_path' => __DIR__ . '/../seld/jsonlint',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'seld/phar-utils' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'reference' => '8674b1d84ffb47cc59a101f5d5a3b61e87d23796',
            'type' => 'library',
            'install_path' => __DIR__ . '/../seld/phar-utils',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'slevomat/coding-standard' => array(
            'pretty_version' => '7.2.1',
            'version' => '7.2.1.0',
            'reference' => 'aff06ae7a84e4534bf6f821dc982a93a5d477c90',
            'type' => 'phpcodesniffer-standard',
            'install_path' => __DIR__ . '/../slevomat/coding-standard',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'spatie/array-to-xml' => array(
            'pretty_version' => '2.16.0',
            'version' => '2.16.0.0',
            'reference' => 'db39308c5236b69b89cadc3f44f191704814eae2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/array-to-xml',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'spatie/backtrace' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'reference' => '9b4df807fb65aaa8006dcd7a7ccdef8fb4bb002e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/backtrace',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'spatie/data-transfer-object' => array(
            'pretty_version' => '3.3.0',
            'version' => '3.3.0.0',
            'reference' => 'ad1547a1d35e81051520955c9f02f0eaafeb2ab9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/data-transfer-object',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'spatie/db-dumper' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'reference' => '1364325f3f3c5b7cdafd46bca5e9d422227a34d2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/db-dumper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'spatie/laravel-activitylog' => array(
            'pretty_version' => '4.0.0',
            'version' => '4.0.0.0',
            'reference' => 'f1e8e8ea2cb85945d5ac770e979b0381cc82da52',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/laravel-activitylog',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'spatie/laravel-backup' => array(
            'pretty_version' => '7.6.0',
            'version' => '7.6.0.0',
            'reference' => '39dc00988cd28e7cd06237dae27bf463fa9420fd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/laravel-backup',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'spatie/laravel-multitenancy' => array(
            'pretty_version' => '2.1.1',
            'version' => '2.1.1.0',
            'reference' => 'e7a30c546e1dacbeff7e89dd6f11dbdf3a36eadd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/laravel-multitenancy',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'spatie/laravel-package-tools' => array(
            'pretty_version' => '1.9.0',
            'version' => '1.9.0.0',
            'reference' => 'cf4c4cec220575e2864c6082842d76822421f1b1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/laravel-package-tools',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'spatie/laravel-permission' => array(
            'pretty_version' => '4.2.0',
            'version' => '4.2.0.0',
            'reference' => 'a6e4122b65094baba7f98df153af0768ef910c85',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/laravel-permission',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'spatie/laravel-ray' => array(
            'pretty_version' => '1.23.0',
            'version' => '1.23.0.0',
            'reference' => '2e49e83f3df25e4ef7a145cb0247d2038b8d3436',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/laravel-ray',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'spatie/laravel-responsecache' => array(
            'pretty_version' => '7.1.0',
            'version' => '7.1.0.0',
            'reference' => '3bf314f2e6ed7644b9dc182817b48754c928008c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/laravel-responsecache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'spatie/laravel-settings' => array(
            'pretty_version' => '2.1.8',
            'version' => '2.1.8.0',
            'reference' => '70d8391845590c72755609f3fbf249857d000828',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/laravel-settings',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'spatie/laravel-signal-aware-command' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'reference' => '8c605808028943da9f6c0064d3fd16358526bcad',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/laravel-signal-aware-command',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'spatie/macroable' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => 'ec2c320f932e730607aff8052c44183cf3ecb072',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/macroable',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'spatie/ray' => array(
            'pretty_version' => '1.28.0',
            'version' => '1.28.0.0',
            'reference' => 'b800636fb022b93df53bd90fa52e5ed07221eb6a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/ray',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'spatie/temporary-directory' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => '06fe0f10d068fdf145c9b2235030e568c913bb61',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/temporary-directory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'squizlabs/php_codesniffer' => array(
            'pretty_version' => '3.7.1',
            'version' => '3.7.1.0',
            'reference' => '1359e176e9307e906dc3d890bcc9603ff6d90619',
            'type' => 'library',
            'install_path' => __DIR__ . '/../squizlabs/php_codesniffer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'swiftmailer/swiftmailer' => array(
            'pretty_version' => 'v6.2.7',
            'version' => '6.2.7.0',
            'reference' => '15f7faf8508e04471f666633addacf54c0ab5933',
            'type' => 'library',
            'install_path' => __DIR__ . '/../swiftmailer/swiftmailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/cache' => array(
            'pretty_version' => 'v5.4.11',
            'version' => '5.4.11.0',
            'reference' => '5a0fff46df349f0db3fe242263451fddf5277362',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/cache',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/cache-contracts' => array(
            'pretty_version' => 'v2.5.2',
            'version' => '2.5.2.0',
            'reference' => '64be4a7acb83b6f2bf6de9a02cee6dad41277ebc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/cache-contracts',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/cache-implementation' => array(
            'dev_requirement' => true,
            'provided' => array(
                0 => '1.0|2.0',
            ),
        ),
        'symfony/console' => array(
            'pretty_version' => 'v5.4.12',
            'version' => '5.4.12.0',
            'reference' => 'c072aa8f724c3af64e2c7a96b796a4863d24dba1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/css-selector' => array(
            'pretty_version' => 'v5.3.0',
            'version' => '5.3.0.0',
            'reference' => 'fcd0b29a7a0b1bb5bfbedc6231583d77fea04814',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/css-selector',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v2.5.2',
            'version' => '2.5.2.0',
            'reference' => 'e8b495ea28c1d97b5e0c121748d6f9b53d075c66',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/error-handler' => array(
            'pretty_version' => 'v5.3.3',
            'version' => '5.3.3.0',
            'reference' => '43323e79c80719e8a4674e33484bca98270d223f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/error-handler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher' => array(
            'pretty_version' => 'v5.4.9',
            'version' => '5.4.9.0',
            'reference' => '8e6ce1cc0279e3ff3c8ff0f43813bc88d21ca1bc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-contracts' => array(
            'pretty_version' => 'v3.0.2',
            'version' => '3.0.2.0',
            'reference' => '7bc61cc2db649b4637d331240c5346dcc7708051',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.0',
            ),
        ),
        'symfony/filesystem' => array(
            'pretty_version' => 'v6.0.12',
            'version' => '6.0.12.0',
            'reference' => 'a36b782dc19dce3ab7e47d4b92b13cefb3511da3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/filesystem',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/finder' => array(
            'pretty_version' => 'v5.4.11',
            'version' => '5.4.11.0',
            'reference' => '7872a66f57caffa2916a584db1aa7f12adc76f8c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/finder',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/http-client' => array(
            'pretty_version' => 'v5.4.12',
            'version' => '5.4.12.0',
            'reference' => '6a057be154824487fd5e6b65ab83899e0c5ac550',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-client',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/http-client-contracts' => array(
            'pretty_version' => 'v2.5.2',
            'version' => '2.5.2.0',
            'reference' => 'ba6a9f0e8f3edd190520ee3b9a958596b6ca2e70',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-client-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/http-client-implementation' => array(
            'dev_requirement' => true,
            'provided' => array(
                0 => '2.4',
            ),
        ),
        'symfony/http-foundation' => array(
            'pretty_version' => 'v5.3.3',
            'version' => '5.3.3.0',
            'reference' => '0e45ab1574caa0460d9190871a8ce47539e40ccf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-foundation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/http-kernel' => array(
            'pretty_version' => 'v5.3.3',
            'version' => '5.3.3.0',
            'reference' => '90ad9f4b21ddcb8ebe9faadfcca54929ad23f9f8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-kernel',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/mime' => array(
            'pretty_version' => 'v5.3.2',
            'version' => '5.3.2.0',
            'reference' => '47dd7912152b82d0d4c8d9040dbc93d6232d472a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/mime',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/options-resolver' => array(
            'pretty_version' => 'v6.0.3',
            'version' => '6.0.3.0',
            'reference' => '51f7006670febe4cbcbae177cbffe93ff833250d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/options-resolver',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.26.0',
            'version' => '1.26.0.0',
            'reference' => '6fd1b9a79f6e3cf65f9e679b23af304cd9e010d4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-iconv' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'reference' => '63b5bb7db83e5673936d6e3b8b3e022ff6474933',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-iconv',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-grapheme' => array(
            'pretty_version' => 'v1.26.0',
            'version' => '1.26.0.0',
            'reference' => '433d05519ce6990bf3530fba6957499d327395c2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-grapheme',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'reference' => '65bd267525e82759e7d8c4e8ceea44f398838e65',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-idn',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.26.0',
            'version' => '1.26.0.0',
            'reference' => '219aa369ceff116e673852dce47c3a41794c14bd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.26.0',
            'version' => '1.26.0.0',
            'reference' => '9344f9cb97f3b19424af1a21a3b0e75b0a7d8d7e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php72' => array(
            'pretty_version' => 'v1.26.0',
            'version' => '1.26.0.0',
            'reference' => 'bf44a9fd41feaac72b074de600314a93e2ae78e2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php72',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php73' => array(
            'pretty_version' => 'v1.26.0',
            'version' => '1.26.0.0',
            'reference' => 'e440d35fa0286f77fb45b79a03fedbeda9307e85',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php73',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.26.0',
            'version' => '1.26.0.0',
            'reference' => 'cfa0ae98841b9e461207c13ab093d76b0fa7bace',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php81' => array(
            'pretty_version' => 'v1.26.0',
            'version' => '1.26.0.0',
            'reference' => '13f6d1271c663dc5ae9fb843a8f16521db7687a1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php81',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/process' => array(
            'pretty_version' => 'v5.4.11',
            'version' => '5.4.11.0',
            'reference' => '6e75fe6874cbc7e4773d049616ab450eff537bf1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/process',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/psr-http-message-bridge' => array(
            'pretty_version' => 'v2.1.0',
            'version' => '2.1.0.0',
            'reference' => '81db2d4ae86e9f0049828d9343a72b9523884e5d',
            'type' => 'symfony-bridge',
            'install_path' => __DIR__ . '/../symfony/psr-http-message-bridge',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/routing' => array(
            'pretty_version' => 'v5.3.0',
            'version' => '5.3.0.0',
            'reference' => '368e81376a8e049c37cb80ae87dbfbf411279199',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/routing',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => 'v2.5.2',
            'version' => '2.5.2.0',
            'reference' => '4b426aac47d6427cc1a1d0f7e2ac724627f5966c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/stopwatch' => array(
            'pretty_version' => 'v5.4.5',
            'version' => '5.4.5.0',
            'reference' => '4d04b5c24f3c9a1a168a131f6cbe297155bc0d30',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/stopwatch',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/string' => array(
            'pretty_version' => 'v6.0.12',
            'version' => '6.0.12.0',
            'reference' => '3a975ba1a1508ad97df45f4590f55b7cc4c1a0a0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/string',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/translation' => array(
            'pretty_version' => 'v5.3.3',
            'version' => '5.3.3.0',
            'reference' => '380b8c9e944d0e364b25f28e8e555241eb49c01c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/translation-contracts' => array(
            'pretty_version' => 'v2.5.2',
            'version' => '2.5.2.0',
            'reference' => '136b19dd05cdf0709db6537d058bcab6dd6e2dbe',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/translation-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.3',
            ),
        ),
        'symfony/var-dumper' => array(
            'pretty_version' => 'v5.3.3',
            'version' => '5.3.3.0',
            'reference' => '46aa709affb9ad3355bd7a810f9662d71025c384',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-dumper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/var-exporter' => array(
            'pretty_version' => 'v6.0.10',
            'version' => '6.0.10.0',
            'reference' => 'e3df004a8d0fb572c420a6915cd23db9254c8366',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-exporter',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v5.3.3',
            'version' => '5.3.3.0',
            'reference' => '485c83a2fb5893e2ff21bf4bfc7fdf48b4967229',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'theseer/tokenizer' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => '34a41e998c2183e22995f158c581e7b5e755ab9e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../theseer/tokenizer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'tijsverkoyen/css-to-inline-styles' => array(
            'pretty_version' => '2.2.3',
            'version' => '2.2.3.0',
            'reference' => 'b43b05cf43c1b6d849478965062b6ef73e223bb5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tijsverkoyen/css-to-inline-styles',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'vlucas/phpdotenv' => array(
            'pretty_version' => 'v5.3.0',
            'version' => '5.3.0.0',
            'reference' => 'b3eac5c7ac896e52deab4a99068e3f4ab12d9e56',
            'type' => 'library',
            'install_path' => __DIR__ . '/../vlucas/phpdotenv',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'voku/portable-ascii' => array(
            'pretty_version' => '1.5.6',
            'version' => '1.5.6.0',
            'reference' => '80953678b19901e5165c56752d087fc11526017c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../voku/portable-ascii',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'vyuldashev/xml-to-array' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'ae1713b167093716b8e8d56bfb318befac4a8c4b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../vyuldashev/xml-to-array',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webmozart/assert' => array(
            'pretty_version' => '1.11.0',
            'version' => '1.11.0.0',
            'reference' => '11cb2199493b2f8a3b53e7f19068fc6aac760991',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webmozart/assert',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'widmogrod/php-functional' => array(
            'pretty_version' => '6.0.0',
            'version' => '6.0.0.0',
            'reference' => 'a1a4edc7f135c4b9364afadcb23d91629255b06c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../widmogrod/php-functional',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'zbateson/mail-mime-parser' => array(
            'pretty_version' => '1.3.1',
            'version' => '1.3.1.0',
            'reference' => '706964d904798b8c22d63f62f0ec5f5bc84e30d9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../zbateson/mail-mime-parser',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'zbateson/mb-wrapper' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '721b3dfbf7ab75fee5ac60a542d7923ffe59ef6d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../zbateson/mb-wrapper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'zbateson/stream-decorators' => array(
            'pretty_version' => '1.0.4',
            'version' => '1.0.4.0',
            'reference' => '6f54738dfecc65e1d5bfb855035836748083a6dd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../zbateson/stream-decorators',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
