<?php return array(
    'root' => array(
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => '19c6c53e848cc36113e95b936418a9cc2597c6f9',
        'name' => 'laravel/laravel',
        'dev' => true,
    ),
    'versions' => array(
        'asm89/stack-cors' => array(
            'pretty_version' => 'v2.0.3',
            'version' => '2.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../asm89/stack-cors',
            'aliases' => array(),
            'reference' => '9cb795bf30988e8c96dd3c40623c48a877bc6714',
            'dev_requirement' => false,
        ),
        'aws/aws-crt-php' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../aws/aws-crt-php',
            'aliases' => array(),
            'reference' => '3942776a8c99209908ee0b287746263725685732',
            'dev_requirement' => false,
        ),
        'aws/aws-sdk-php' => array(
            'pretty_version' => '3.209.10',
            'version' => '3.209.10.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../aws/aws-sdk-php',
            'aliases' => array(),
            'reference' => '45082e9fac26bdbc5db504639373374084f616d3',
            'dev_requirement' => false,
        ),
        'barryvdh/laravel-dompdf' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../barryvdh/laravel-dompdf',
            'aliases' => array(),
            'reference' => 'e3f429e97087b2ef19b83e5ed313f080f2477685',
            'dev_requirement' => false,
        ),
        'barryvdh/laravel-ide-helper' => array(
            'pretty_version' => 'v2.10.0',
            'version' => '2.10.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../barryvdh/laravel-ide-helper',
            'aliases' => array(),
            'reference' => '73b1012b927633a1b4cd623c2e6b1678e6faef08',
            'dev_requirement' => false,
        ),
        'barryvdh/reflection-docblock' => array(
            'pretty_version' => 'v2.0.6',
            'version' => '2.0.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../barryvdh/reflection-docblock',
            'aliases' => array(),
            'reference' => '6b69015d83d3daf9004a71a89f26e27d27ef6a16',
            'dev_requirement' => false,
        ),
        'beberlei/assert' => array(
            'pretty_version' => 'v3.3.2',
            'version' => '3.3.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../beberlei/assert',
            'aliases' => array(),
            'reference' => 'cb70015c04be1baee6f5f5c953703347c0ac1655',
            'dev_requirement' => false,
        ),
        'brianium/paratest' => array(
            'pretty_version' => 'v6.3.0',
            'version' => '6.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../brianium/paratest',
            'aliases' => array(),
            'reference' => '268d5b2b4237c0abf76c4aa9633ad8580be01e1e',
            'dev_requirement' => true,
        ),
        'brick/math' => array(
            'pretty_version' => '0.9.2',
            'version' => '0.9.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../brick/math',
            'aliases' => array(),
            'reference' => 'dff976c2f3487d42c1db75a3b180e2b9f0e72ce0',
            'dev_requirement' => false,
        ),
        'composer/ca-bundle' => array(
            'pretty_version' => '1.2.10',
            'version' => '1.2.10.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/./ca-bundle',
            'aliases' => array(),
            'reference' => '9fdb22c2e97a614657716178093cd1da90a64aa8',
            'dev_requirement' => false,
        ),
        'composer/composer' => array(
            'pretty_version' => '2.1.3',
            'version' => '2.1.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/./composer',
            'aliases' => array(),
            'reference' => 'fc5c4573aafce3a018eb7f1f8f91cea423970f2e',
            'dev_requirement' => false,
        ),
        'composer/metadata-minifier' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/./metadata-minifier',
            'aliases' => array(),
            'reference' => 'c549d23829536f0d0e984aaabbf02af91f443207',
            'dev_requirement' => false,
        ),
        'composer/package-versions-deprecated' => array(
            'pretty_version' => '1.11.99.2',
            'version' => '1.11.99.2',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/./package-versions-deprecated',
            'aliases' => array(),
            'reference' => 'c6522afe5540d5fc46675043d3ed5a45a740b27c',
            'dev_requirement' => false,
        ),
        'composer/semver' => array(
            'pretty_version' => '3.2.5',
            'version' => '3.2.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/./semver',
            'aliases' => array(),
            'reference' => '31f3ea725711245195f62e54ffa402d8ef2fdba9',
            'dev_requirement' => false,
        ),
        'composer/spdx-licenses' => array(
            'pretty_version' => '1.5.5',
            'version' => '1.5.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/./spdx-licenses',
            'aliases' => array(),
            'reference' => 'de30328a7af8680efdc03e396aad24befd513200',
            'dev_requirement' => false,
        ),
        'composer/xdebug-handler' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/./xdebug-handler',
            'aliases' => array(),
            'reference' => '964adcdd3a28bf9ed5d9ac6450064e0d71ed7496',
            'dev_requirement' => false,
        ),
        'cordoval/hamcrest-php' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'davedevelopment/hamcrest-php' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'defuse/php-encryption' => array(
            'pretty_version' => 'v2.3.1',
            'version' => '2.3.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../defuse/php-encryption',
            'aliases' => array(),
            'reference' => '77880488b9954b7884c25555c2a0ea9e7053f9d2',
            'dev_requirement' => false,
        ),
        'doctrine/cache' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/cache',
            'aliases' => array(),
            'reference' => 'c9622c6820d3ede1e2315a6a377ea1076e421d88',
            'dev_requirement' => false,
        ),
        'doctrine/dbal' => array(
            'pretty_version' => '3.1.1',
            'version' => '3.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/dbal',
            'aliases' => array(),
            'reference' => '8e0fde2b90e3f61361013d1e928621beeea07bc0',
            'dev_requirement' => false,
        ),
        'doctrine/deprecations' => array(
            'pretty_version' => 'v0.5.3',
            'version' => '0.5.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/deprecations',
            'aliases' => array(),
            'reference' => '9504165960a1f83cc1480e2be1dd0a0478561314',
            'dev_requirement' => false,
        ),
        'doctrine/event-manager' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/event-manager',
            'aliases' => array(),
            'reference' => '41370af6a30faa9dc0368c4a6814d596e81aba7f',
            'dev_requirement' => false,
        ),
        'doctrine/inflector' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/inflector',
            'aliases' => array(),
            'reference' => '9cf661f4eb38f7c881cac67c75ea9b00bf97b210',
            'dev_requirement' => false,
        ),
        'doctrine/instantiator' => array(
            'pretty_version' => '1.4.0',
            'version' => '1.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/instantiator',
            'aliases' => array(),
            'reference' => 'd56bf6102915de5702778fe20f2de3b2fe570b5b',
            'dev_requirement' => true,
        ),
        'doctrine/lexer' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/lexer',
            'aliases' => array(),
            'reference' => 'e864bbf5904cb8f5bb334f99209b48018522f042',
            'dev_requirement' => false,
        ),
        'dompdf/dompdf' => array(
            'pretty_version' => 'v1.1.1',
            'version' => '1.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dompdf/dompdf',
            'aliases' => array(),
            'reference' => 'de4aad040737a89fae2129cdeb0f79c45513128d',
            'dev_requirement' => false,
        ),
        'dragonmantank/cron-expression' => array(
            'pretty_version' => 'v3.1.0',
            'version' => '3.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dragonmantank/cron-expression',
            'aliases' => array(),
            'reference' => '7a8c6e56ab3ffcc538d05e8155bb42269abf1a0c',
            'dev_requirement' => false,
        ),
        'egulias/email-validator' => array(
            'pretty_version' => '2.1.25',
            'version' => '2.1.25.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../egulias/email-validator',
            'aliases' => array(),
            'reference' => '0dbf5d78455d4d6a41d186da50adc1122ec066f4',
            'dev_requirement' => false,
        ),
        'evenement/evenement' => array(
            'pretty_version' => 'v3.0.1',
            'version' => '3.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../evenement/evenement',
            'aliases' => array(),
            'reference' => '531bfb9d15f8aa57454f5f0285b18bec903b8fb7',
            'dev_requirement' => false,
        ),
        'ezyang/htmlpurifier' => array(
            'pretty_version' => 'v4.14.0',
            'version' => '4.14.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezyang/htmlpurifier',
            'aliases' => array(),
            'reference' => '12ab42bd6e742c70c0a52f7b82477fcd44e64b75',
            'dev_requirement' => false,
        ),
        'facade/flare-client-php' => array(
            'pretty_version' => '1.8.1',
            'version' => '1.8.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../facade/flare-client-php',
            'aliases' => array(),
            'reference' => '47b639dc02bcfdfc4ebb83de703856fa01e35f5f',
            'dev_requirement' => true,
        ),
        'facade/ignition' => array(
            'pretty_version' => '2.10.2',
            'version' => '2.10.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../facade/ignition',
            'aliases' => array(),
            'reference' => '43688227bbf27c43bc1ad83af224f135b6ef0ff4',
            'dev_requirement' => true,
        ),
        'facade/ignition-contracts' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../facade/ignition-contracts',
            'aliases' => array(),
            'reference' => '3c921a1cdba35b68a7f0ccffc6dffc1995b18267',
            'dev_requirement' => true,
        ),
        'fakerphp/faker' => array(
            'pretty_version' => 'v1.15.0',
            'version' => '1.15.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fakerphp/faker',
            'aliases' => array(),
            'reference' => '89c6201c74db25fa759ff16e78a4d8f32547770e',
            'dev_requirement' => true,
        ),
        'fideloper/proxy' => array(
            'pretty_version' => '4.4.1',
            'version' => '4.4.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fideloper/proxy',
            'aliases' => array(),
            'reference' => 'c073b2bd04d1c90e04dc1b787662b558dd65ade0',
            'dev_requirement' => false,
        ),
        'filp/whoops' => array(
            'pretty_version' => '2.13.0',
            'version' => '2.13.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../filp/whoops',
            'aliases' => array(),
            'reference' => '2edbc73a4687d9085c8f20f398eebade844e8424',
            'dev_requirement' => true,
        ),
        'firebase/php-jwt' => array(
            'pretty_version' => 'v5.4.0',
            'version' => '5.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../firebase/php-jwt',
            'aliases' => array(),
            'reference' => 'd2113d9b2e0e349796e72d2a63cf9319100382d2',
            'dev_requirement' => false,
        ),
        'flix-tech/avro-php' => array(
            'pretty_version' => '4.2.0',
            'version' => '4.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../flix-tech/avro-php',
            'aliases' => array(),
            'reference' => 'd56613999a042c26dad8d5f2d53012cd3db4b8f7',
            'dev_requirement' => false,
        ),
        'flix-tech/avro-serde-php' => array(
            'pretty_version' => '1.7.1',
            'version' => '1.7.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../flix-tech/avro-serde-php',
            'aliases' => array(),
            'reference' => 'fabd439f31b0d0fbd0f9bb70c13ad04efd16cd83',
            'dev_requirement' => false,
        ),
        'flix-tech/confluent-schema-registry-api' => array(
            'pretty_version' => '7.5.1',
            'version' => '7.5.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../flix-tech/confluent-schema-registry-api',
            'aliases' => array(),
            'reference' => '300bf29d61ed50e91a11ef12aa51dd53800aab6e',
            'dev_requirement' => false,
        ),
        'fruitcake/laravel-cors' => array(
            'pretty_version' => 'v2.0.4',
            'version' => '2.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fruitcake/laravel-cors',
            'aliases' => array(),
            'reference' => 'a8ccedc7ca95189ead0e407c43b530dc17791d6a',
            'dev_requirement' => false,
        ),
        'functional-php/fantasy-land' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../functional-php/fantasy-land',
            'aliases' => array(),
            'reference' => '1e2366e68057bbc7a65d58dd663324eb9b299775',
            'dev_requirement' => false,
        ),
        'graham-campbell/result-type' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../graham-campbell/result-type',
            'aliases' => array(),
            'reference' => '7e279d2cd5d7fbb156ce46daada972355cea27bb',
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '7.4.1',
            'version' => '7.4.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'reference' => 'ee0a041b1760e6a53d2a39c8c34115adc2af2c79',
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '1.5.1',
            'version' => '1.5.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'reference' => 'fe752aedc9fd8fcca3fe7ad05d419d32998a06da',
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '1.8.3',
            'version' => '1.8.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'reference' => '1afdd860a2566ed3c2b0b4a3de6e23434a79ec85',
            'dev_requirement' => false,
        ),
        'hamcrest/hamcrest-php' => array(
            'pretty_version' => 'v2.0.1',
            'version' => '2.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../hamcrest/hamcrest-php',
            'aliases' => array(),
            'reference' => '8c3d0a3f6af734494ad8f6fbbee0ba92422859f3',
            'dev_requirement' => false,
        ),
        'illuminate/auth' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/broadcasting' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/bus' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/cache' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/collections' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/config' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/console' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/container' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/contracts' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/cookie' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/database' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/encryption' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/events' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/filesystem' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/hashing' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/http' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/log' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/macroable' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/mail' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/notifications' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/pagination' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/pipeline' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/queue' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/redis' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/routing' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/session' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/support' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/testing' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/translation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/validation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'illuminate/view' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v8.49.2',
            ),
        ),
        'jean85/pretty-package-versions' => array(
            'pretty_version' => '1.6.0',
            'version' => '1.6.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jean85/pretty-package-versions',
            'aliases' => array(),
            'reference' => '1e0104b46f045868f11942aea058cd7186d6c303',
            'dev_requirement' => false,
        ),
        'jenssegers/mongodb' => array(
            'pretty_version' => '3.8.4',
            'version' => '3.8.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jenssegers/mongodb',
            'aliases' => array(),
            'reference' => '6aa6ad12b3b52eeab1d090f282c14123ffad1dc9',
            'dev_requirement' => false,
        ),
        'justinrainbow/json-schema' => array(
            'pretty_version' => '5.2.10',
            'version' => '5.2.10.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../justinrainbow/json-schema',
            'aliases' => array(),
            'reference' => '2ba9c8c862ecd5510ed16c6340aa9f6eadb4f31b',
            'dev_requirement' => false,
        ),
        'kodova/hamcrest-php' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'laravel/framework' => array(
            'pretty_version' => 'v8.49.2',
            'version' => '8.49.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel/framework',
            'aliases' => array(),
            'reference' => 'd9b43ee080b4d51344b2e578aa667f85040471a2',
            'dev_requirement' => false,
        ),
        'laravel/horizon' => array(
            'pretty_version' => 'v5.7.9',
            'version' => '5.7.9.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel/horizon',
            'aliases' => array(),
            'reference' => '50dc53b105ec612cf1a87e89fffd21cc0a43003c',
            'dev_requirement' => false,
        ),
        'laravel/laravel' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => '19c6c53e848cc36113e95b936418a9cc2597c6f9',
            'dev_requirement' => false,
        ),
        'laravel/passport' => array(
            'pretty_version' => 'v10.1.3',
            'version' => '10.1.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel/passport',
            'aliases' => array(),
            'reference' => 'a5e4471dd99b7638ab5ca3ecab6cd87cf37eb410',
            'dev_requirement' => false,
        ),
        'laravel/telescope' => array(
            'pretty_version' => 'v4.5.1',
            'version' => '4.5.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel/telescope',
            'aliases' => array(),
            'reference' => '77373b6dccfc0c4372f1a09c9064cbe7b6d1bf76',
            'dev_requirement' => false,
        ),
        'laravel/tinker' => array(
            'pretty_version' => 'v2.6.1',
            'version' => '2.6.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel/tinker',
            'aliases' => array(),
            'reference' => '04ad32c1a3328081097a181875733fa51f402083',
            'dev_requirement' => false,
        ),
        'laravel/ui' => array(
            'pretty_version' => 'v3.3.0',
            'version' => '3.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel/ui',
            'aliases' => array(),
            'reference' => '07d725813350c695c779382cbd6dac0ab8665537',
            'dev_requirement' => false,
        ),
        'lcobucci/clock' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../lcobucci/clock',
            'aliases' => array(),
            'reference' => '353d83fe2e6ae95745b16b3d911813df6a05bfb3',
            'dev_requirement' => false,
        ),
        'lcobucci/jwt' => array(
            'pretty_version' => '4.1.4',
            'version' => '4.1.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../lcobucci/jwt',
            'aliases' => array(),
            'reference' => '71cf170102c8371ccd933fa4df6252086d144de6',
            'dev_requirement' => false,
        ),
        'league/commonmark' => array(
            'pretty_version' => '1.6.5',
            'version' => '1.6.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/commonmark',
            'aliases' => array(),
            'reference' => '44ffd8d3c4a9133e4bd0548622b09c55af39db5f',
            'dev_requirement' => false,
        ),
        'league/event' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/event',
            'aliases' => array(),
            'reference' => 'd2cc124cf9a3fab2bb4ff963307f60361ce4d119',
            'dev_requirement' => false,
        ),
        'league/flysystem' => array(
            'pretty_version' => '1.1.9',
            'version' => '1.1.9.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/flysystem',
            'aliases' => array(),
            'reference' => '094defdb4a7001845300334e7c1ee2335925ef99',
            'dev_requirement' => false,
        ),
        'league/flysystem-aws-s3-v3' => array(
            'pretty_version' => '1.0.29',
            'version' => '1.0.29.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/flysystem-aws-s3-v3',
            'aliases' => array(),
            'reference' => '4e25cc0582a36a786c31115e419c6e40498f6972',
            'dev_requirement' => false,
        ),
        'league/mime-type-detection' => array(
            'pretty_version' => '1.9.0',
            'version' => '1.9.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/mime-type-detection',
            'aliases' => array(),
            'reference' => 'aa70e813a6ad3d1558fc927863d47309b4c23e69',
            'dev_requirement' => false,
        ),
        'league/oauth2-server' => array(
            'pretty_version' => '8.2.4',
            'version' => '8.2.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/oauth2-server',
            'aliases' => array(),
            'reference' => '622eaa1f28eb4a2dea0cfc7e4f5280fac794e83c',
            'dev_requirement' => false,
        ),
        'league/oauth2server' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'lncd/oauth2' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'maennchen/zipstream-php' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maennchen/zipstream-php',
            'aliases' => array(),
            'reference' => 'c4c5803cc1f93df3d2448478ef79394a5981cc58',
            'dev_requirement' => false,
        ),
        'markbaker/complex' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/complex',
            'aliases' => array(),
            'reference' => 'ab8bc271e404909db09ff2d5ffa1e538085c0f22',
            'dev_requirement' => false,
        ),
        'markbaker/matrix' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/matrix',
            'aliases' => array(),
            'reference' => 'c66aefcafb4f6c269510e9ac46b82619a904c576',
            'dev_requirement' => false,
        ),
        'mateusjunges/laravel-kafka' => array(
            'pretty_version' => 'v1.7.0',
            'version' => '1.7.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mateusjunges/laravel-kafka',
            'aliases' => array(),
            'reference' => '504b27509e79c141974a8b99c20003885a6dbc7d',
            'dev_requirement' => false,
        ),
        'mockery/mockery' => array(
            'pretty_version' => '1.4.3',
            'version' => '1.4.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mockery/mockery',
            'aliases' => array(),
            'reference' => 'd1339f64479af1bee0e82a0413813fe5345a54ea',
            'dev_requirement' => false,
        ),
        'mongodb/mongodb' => array(
            'pretty_version' => '1.8.0',
            'version' => '1.8.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mongodb/mongodb',
            'aliases' => array(),
            'reference' => '953dbc19443aa9314c44b7217a16873347e6840d',
            'dev_requirement' => false,
        ),
        'monolog/monolog' => array(
            'pretty_version' => '2.3.0',
            'version' => '2.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../monolog/monolog',
            'aliases' => array(),
            'reference' => 'df991fd88693ab703aa403413d83e15f688dae33',
            'dev_requirement' => false,
        ),
        'mtdowling/cron-expression' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '^1.0',
            ),
        ),
        'mtdowling/jmespath.php' => array(
            'pretty_version' => '2.6.1',
            'version' => '2.6.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mtdowling/jmespath.php',
            'aliases' => array(),
            'reference' => '9b87907a81b87bc76d19a7fb2d61e61486ee9edb',
            'dev_requirement' => false,
        ),
        'myclabs/deep-copy' => array(
            'pretty_version' => '1.10.2',
            'version' => '1.10.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/deep-copy',
            'aliases' => array(),
            'reference' => '776f831124e9c62e1a2c601ecc52e776d8bb7220',
            'dev_requirement' => true,
            'replaced' => array(
                0 => '1.10.2',
            ),
        ),
        'myclabs/php-enum' => array(
            'pretty_version' => '1.8.3',
            'version' => '1.8.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/php-enum',
            'aliases' => array(),
            'reference' => 'b942d263c641ddb5190929ff840c68f78713e937',
            'dev_requirement' => false,
        ),
        'nesbot/carbon' => array(
            'pretty_version' => '2.50.0',
            'version' => '2.50.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nesbot/carbon',
            'aliases' => array(),
            'reference' => 'f47f17d17602b2243414a44ad53d9f8b9ada5fdb',
            'dev_requirement' => false,
        ),
        'nikic/php-parser' => array(
            'pretty_version' => 'v4.11.0',
            'version' => '4.11.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'reference' => 'fe14cf3672a149364fb66dfe11bf6549af899f94',
            'dev_requirement' => false,
        ),
        'nunomaduro/collision' => array(
            'pretty_version' => 'v5.5.0',
            'version' => '5.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nunomaduro/collision',
            'aliases' => array(),
            'reference' => 'b5cb36122f1c142c3c3ee20a0ae778439ef0244b',
            'dev_requirement' => true,
        ),
        'nunomaduro/larastan' => array(
            'pretty_version' => 'v0.7.10',
            'version' => '0.7.10.0',
            'type' => 'phpstan-extension',
            'install_path' => __DIR__ . '/../nunomaduro/larastan',
            'aliases' => array(),
            'reference' => 'd684efa6f79ff34f3a516efa9db532c861438718',
            'dev_requirement' => true,
        ),
        'nyholm/psr7' => array(
            'pretty_version' => '1.4.1',
            'version' => '1.4.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nyholm/psr7',
            'aliases' => array(),
            'reference' => '2212385b47153ea71b1c1b1374f8cb5e4f7892ec',
            'dev_requirement' => false,
        ),
        'ocramius/package-versions' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.11.99',
            ),
        ),
        'opis/closure' => array(
            'pretty_version' => '3.6.2',
            'version' => '3.6.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../opis/closure',
            'aliases' => array(),
            'reference' => '06e2ebd25f2869e54a306dda991f7db58066f7f6',
            'dev_requirement' => false,
        ),
        'paragonie/constant_time_encoding' => array(
            'pretty_version' => 'v2.4.0',
            'version' => '2.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/constant_time_encoding',
            'aliases' => array(),
            'reference' => 'f34c2b11eb9d2c9318e13540a1dbc2a3afbd939c',
            'dev_requirement' => false,
        ),
        'paragonie/random_compat' => array(
            'pretty_version' => 'v9.99.100',
            'version' => '9.99.100.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/random_compat',
            'aliases' => array(),
            'reference' => '996434e5492cb4c3edcb9168db6fbb1359ef965a',
            'dev_requirement' => false,
        ),
        'phar-io/manifest' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/manifest',
            'aliases' => array(),
            'reference' => '85265efd3af7ba3ca4b2a2c34dbfc5788dd29133',
            'dev_requirement' => true,
        ),
        'phar-io/version' => array(
            'pretty_version' => '3.1.0',
            'version' => '3.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/version',
            'aliases' => array(),
            'reference' => 'bae7c545bef187884426f042434e561ab1ddb182',
            'dev_requirement' => true,
        ),
        'phenx/php-font-lib' => array(
            'pretty_version' => '0.5.2',
            'version' => '0.5.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phenx/php-font-lib',
            'aliases' => array(),
            'reference' => 'ca6ad461f032145fff5971b5985e5af9e7fa88d8',
            'dev_requirement' => false,
        ),
        'phenx/php-svg-lib' => array(
            'pretty_version' => '0.3.4',
            'version' => '0.3.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phenx/php-svg-lib',
            'aliases' => array(),
            'reference' => 'f627771eb854aa7f45f80add0f23c6c4d67ea0f2',
            'dev_requirement' => false,
        ),
        'php-http/message-factory' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/message-factory',
            'aliases' => array(),
            'reference' => 'a478cb11f66a6ac48d8954216cfed9aa06a501a1',
            'dev_requirement' => false,
        ),
        'phpdocumentor/reflection-common' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-common',
            'aliases' => array(),
            'reference' => '1d01c49d4ed62f25aa84a747ad35d5a16924662b',
            'dev_requirement' => false,
        ),
        'phpdocumentor/reflection-docblock' => array(
            'pretty_version' => '5.2.2',
            'version' => '5.2.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-docblock',
            'aliases' => array(),
            'reference' => '069a785b2141f5bcf49f3e353548dc1cce6df556',
            'dev_requirement' => true,
        ),
        'phpdocumentor/type-resolver' => array(
            'pretty_version' => '1.4.0',
            'version' => '1.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/type-resolver',
            'aliases' => array(),
            'reference' => '6a467b8989322d92aa1c8bf2bebcc6e5c2ba55c0',
            'dev_requirement' => false,
        ),
        'phpoffice/phpspreadsheet' => array(
            'pretty_version' => '1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoffice/phpspreadsheet',
            'aliases' => array(),
            'reference' => '21e4cf62699eebf007db28775f7d1554e612ed9e',
            'dev_requirement' => false,
        ),
        'phpoption/phpoption' => array(
            'pretty_version' => '1.7.5',
            'version' => '1.7.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoption/phpoption',
            'aliases' => array(),
            'reference' => '994ecccd8f3283ecf5ac33254543eb0ac946d525',
            'dev_requirement' => false,
        ),
        'phpseclib/phpseclib' => array(
            'pretty_version' => '3.0.9',
            'version' => '3.0.9.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpseclib/phpseclib',
            'aliases' => array(),
            'reference' => 'a127a5133804ff2f47ae629dd529b129da616ad7',
            'dev_requirement' => false,
        ),
        'phpspec/prophecy' => array(
            'pretty_version' => '1.13.0',
            'version' => '1.13.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpspec/prophecy',
            'aliases' => array(),
            'reference' => 'be1996ed8adc35c3fd795488a653f4b518be70ea',
            'dev_requirement' => true,
        ),
        'phpstan/phpstan' => array(
            'pretty_version' => '0.12.91',
            'version' => '0.12.91.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpstan/phpstan',
            'aliases' => array(),
            'reference' => '8226701cd228a0d63c2df995de7ab6070c69ac6a',
            'dev_requirement' => true,
        ),
        'phpunit/php-code-coverage' => array(
            'pretty_version' => '9.2.6',
            'version' => '9.2.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-code-coverage',
            'aliases' => array(),
            'reference' => 'f6293e1b30a2354e8428e004689671b83871edde',
            'dev_requirement' => true,
        ),
        'phpunit/php-file-iterator' => array(
            'pretty_version' => '3.0.5',
            'version' => '3.0.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-file-iterator',
            'aliases' => array(),
            'reference' => 'aa4be8575f26070b100fccb67faabb28f21f66f8',
            'dev_requirement' => true,
        ),
        'phpunit/php-invoker' => array(
            'pretty_version' => '3.1.1',
            'version' => '3.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-invoker',
            'aliases' => array(),
            'reference' => '5a10147d0aaf65b58940a0b72f71c9ac0423cc67',
            'dev_requirement' => true,
        ),
        'phpunit/php-text-template' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-text-template',
            'aliases' => array(),
            'reference' => '5da5f67fc95621df9ff4c4e5a84d6a8a2acf7c28',
            'dev_requirement' => true,
        ),
        'phpunit/php-timer' => array(
            'pretty_version' => '5.0.3',
            'version' => '5.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-timer',
            'aliases' => array(),
            'reference' => '5a63ce20ed1b5bf577850e2c4e87f4aa902afbd2',
            'dev_requirement' => true,
        ),
        'phpunit/phpunit' => array(
            'pretty_version' => '9.5.6',
            'version' => '9.5.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit',
            'aliases' => array(),
            'reference' => 'fb9b8333f14e3dce976a60ef6a7e05c7c7ed8bfb',
            'dev_requirement' => true,
        ),
        'predis/predis' => array(
            'pretty_version' => 'v1.1.7',
            'version' => '1.1.7.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../predis/predis',
            'aliases' => array(),
            'reference' => 'b240daa106d4e02f0c5b7079b41e31ddf66fddf8',
            'dev_requirement' => false,
        ),
        'psr/container' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'reference' => '8622567409010282b7aeebe4bb841fe98b58dcaf',
            'dev_requirement' => false,
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/event-dispatcher' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/event-dispatcher',
            'aliases' => array(),
            'reference' => 'dbefd12671e8a14ec7f180cab83036ed26714bb0',
            'dev_requirement' => false,
        ),
        'psr/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'reference' => '2dfb5f6c5eff0e91e20e913f8c5452ed95b86621',
            'dev_requirement' => false,
        ),
        'psr/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'reference' => '12ac7fcd07e5b077433f5f2bee95b3a771bf61be',
            'dev_requirement' => false,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'reference' => 'f6561bf28d520154e4b0ec72be95418abe6d9363',
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0.0',
                1 => '1.0',
            ),
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'reference' => '408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
            'dev_requirement' => false,
        ),
        'psy/psysh' => array(
            'pretty_version' => 'v0.10.8',
            'version' => '0.10.8.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psy/psysh',
            'aliases' => array(),
            'reference' => 'e4573f47750dd6c92dca5aee543fa77513cbd8d3',
            'dev_requirement' => false,
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'dev_requirement' => false,
        ),
        'ramsey/collection' => array(
            'pretty_version' => '1.1.3',
            'version' => '1.1.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ramsey/collection',
            'aliases' => array(),
            'reference' => '28a5c4ab2f5111db6a60b2b4ec84057e0f43b9c1',
            'dev_requirement' => false,
        ),
        'ramsey/uuid' => array(
            'pretty_version' => '4.1.1',
            'version' => '4.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ramsey/uuid',
            'aliases' => array(),
            'reference' => 'cd4032040a750077205918c86049aa0f43d22947',
            'dev_requirement' => false,
        ),
        'react/cache' => array(
            'pretty_version' => 'v1.1.1',
            'version' => '1.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/cache',
            'aliases' => array(),
            'reference' => '4bf736a2cccec7298bdf745db77585966fc2ca7e',
            'dev_requirement' => false,
        ),
        'react/dns' => array(
            'pretty_version' => 'v1.7.0',
            'version' => '1.7.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/dns',
            'aliases' => array(),
            'reference' => 'a45784faebf8fbd59058fad2d8497f71a787d20c',
            'dev_requirement' => false,
        ),
        'react/event-loop' => array(
            'pretty_version' => 'v1.1.1',
            'version' => '1.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/event-loop',
            'aliases' => array(),
            'reference' => '6d24de090cd59cfc830263cfba965be77b563c13',
            'dev_requirement' => false,
        ),
        'react/http' => array(
            'pretty_version' => 'v1.2.0',
            'version' => '1.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/http',
            'aliases' => array(),
            'reference' => 'badb0a87890e14b9cdfa3aec3ba1aafd900401ac',
            'dev_requirement' => false,
        ),
        'react/promise' => array(
            'pretty_version' => 'v2.8.0',
            'version' => '2.8.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/promise',
            'aliases' => array(),
            'reference' => 'f3cff96a19736714524ca0dd1d4130de73dbbbc4',
            'dev_requirement' => false,
        ),
        'react/promise-stream' => array(
            'pretty_version' => 'v1.2.0',
            'version' => '1.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/promise-stream',
            'aliases' => array(),
            'reference' => '6384d8b76cf7dcc44b0bf3343fb2b2928412d1fe',
            'dev_requirement' => false,
        ),
        'react/promise-timer' => array(
            'pretty_version' => 'v1.6.0',
            'version' => '1.6.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/promise-timer',
            'aliases' => array(),
            'reference' => 'daee9baf6ef30c43ea4c86399f828bb5f558f6e6',
            'dev_requirement' => false,
        ),
        'react/socket' => array(
            'pretty_version' => 'v1.7.0',
            'version' => '1.7.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/socket',
            'aliases' => array(),
            'reference' => '5d39e3fa56ea7cc443c86f2788a40867cdba1659',
            'dev_requirement' => false,
        ),
        'react/stream' => array(
            'pretty_version' => 'v1.1.1',
            'version' => '1.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/stream',
            'aliases' => array(),
            'reference' => '7c02b510ee3f582c810aeccd3a197b9c2f52ff1a',
            'dev_requirement' => false,
        ),
        'rhumsaa/uuid' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.1.1',
            ),
        ),
        'ringcentral/psr7' => array(
            'pretty_version' => '1.3.0',
            'version' => '1.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ringcentral/psr7',
            'aliases' => array(),
            'reference' => '360faaec4b563958b673fb52bbe94e37f14bc686',
            'dev_requirement' => false,
        ),
        'sabberworm/php-css-parser' => array(
            'pretty_version' => '8.3.1',
            'version' => '8.3.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sabberworm/php-css-parser',
            'aliases' => array(),
            'reference' => 'd217848e1396ef962fb1997cf3e2421acba7f796',
            'dev_requirement' => false,
        ),
        'sebastian/cli-parser' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/cli-parser',
            'aliases' => array(),
            'reference' => '442e7c7e687e42adc03470c7b668bc4b2402c0b2',
            'dev_requirement' => true,
        ),
        'sebastian/code-unit' => array(
            'pretty_version' => '1.0.8',
            'version' => '1.0.8.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit',
            'aliases' => array(),
            'reference' => '1fc9f64c0927627ef78ba436c9b17d967e68e120',
            'dev_requirement' => true,
        ),
        'sebastian/code-unit-reverse-lookup' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit-reverse-lookup',
            'aliases' => array(),
            'reference' => 'ac91f01ccec49fb77bdc6fd1e548bc70f7faa3e5',
            'dev_requirement' => true,
        ),
        'sebastian/comparator' => array(
            'pretty_version' => '4.0.6',
            'version' => '4.0.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/comparator',
            'aliases' => array(),
            'reference' => '55f4261989e546dc112258c7a75935a81a7ce382',
            'dev_requirement' => true,
        ),
        'sebastian/complexity' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/complexity',
            'aliases' => array(),
            'reference' => '739b35e53379900cc9ac327b2147867b8b6efd88',
            'dev_requirement' => true,
        ),
        'sebastian/diff' => array(
            'pretty_version' => '4.0.4',
            'version' => '4.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/diff',
            'aliases' => array(),
            'reference' => '3461e3fccc7cfdfc2720be910d3bd73c69be590d',
            'dev_requirement' => true,
        ),
        'sebastian/environment' => array(
            'pretty_version' => '5.1.3',
            'version' => '5.1.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/environment',
            'aliases' => array(),
            'reference' => '388b6ced16caa751030f6a69e588299fa09200ac',
            'dev_requirement' => true,
        ),
        'sebastian/exporter' => array(
            'pretty_version' => '4.0.3',
            'version' => '4.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/exporter',
            'aliases' => array(),
            'reference' => 'd89cc98761b8cb5a1a235a6b703ae50d34080e65',
            'dev_requirement' => true,
        ),
        'sebastian/global-state' => array(
            'pretty_version' => '5.0.3',
            'version' => '5.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/global-state',
            'aliases' => array(),
            'reference' => '23bd5951f7ff26f12d4e3242864df3e08dec4e49',
            'dev_requirement' => true,
        ),
        'sebastian/lines-of-code' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/lines-of-code',
            'aliases' => array(),
            'reference' => 'c1c2e997aa3146983ed888ad08b15470a2e22ecc',
            'dev_requirement' => true,
        ),
        'sebastian/object-enumerator' => array(
            'pretty_version' => '4.0.4',
            'version' => '4.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-enumerator',
            'aliases' => array(),
            'reference' => '5c9eeac41b290a3712d88851518825ad78f45c71',
            'dev_requirement' => true,
        ),
        'sebastian/object-reflector' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-reflector',
            'aliases' => array(),
            'reference' => 'b4f479ebdbf63ac605d183ece17d8d7fe49c15c7',
            'dev_requirement' => true,
        ),
        'sebastian/recursion-context' => array(
            'pretty_version' => '4.0.4',
            'version' => '4.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/recursion-context',
            'aliases' => array(),
            'reference' => 'cd9d8cf3c5804de4341c283ed787f099f5506172',
            'dev_requirement' => true,
        ),
        'sebastian/resource-operations' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/resource-operations',
            'aliases' => array(),
            'reference' => '0f4443cb3a1d92ce809899753bc0d5d5a8dd19a8',
            'dev_requirement' => true,
        ),
        'sebastian/type' => array(
            'pretty_version' => '2.3.4',
            'version' => '2.3.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/type',
            'aliases' => array(),
            'reference' => 'b8cd8a1c753c90bc1a0f5372170e3e489136f914',
            'dev_requirement' => true,
        ),
        'sebastian/version' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/version',
            'aliases' => array(),
            'reference' => 'c6c1022351a901512170118436c764e473f6de8c',
            'dev_requirement' => true,
        ),
        'seld/jsonlint' => array(
            'pretty_version' => '1.8.3',
            'version' => '1.8.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../seld/jsonlint',
            'aliases' => array(),
            'reference' => '9ad6ce79c342fbd44df10ea95511a1b24dee5b57',
            'dev_requirement' => false,
        ),
        'seld/phar-utils' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../seld/phar-utils',
            'aliases' => array(),
            'reference' => '8674b1d84ffb47cc59a101f5d5a3b61e87d23796',
            'dev_requirement' => false,
        ),
        'spatie/array-to-xml' => array(
            'pretty_version' => '2.16.0',
            'version' => '2.16.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/array-to-xml',
            'aliases' => array(),
            'reference' => 'db39308c5236b69b89cadc3f44f191704814eae2',
            'dev_requirement' => false,
        ),
        'spatie/backtrace' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/backtrace',
            'aliases' => array(),
            'reference' => '9b4df807fb65aaa8006dcd7a7ccdef8fb4bb002e',
            'dev_requirement' => false,
        ),
        'spatie/data-transfer-object' => array(
            'pretty_version' => '3.3.0',
            'version' => '3.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/data-transfer-object',
            'aliases' => array(),
            'reference' => 'ad1547a1d35e81051520955c9f02f0eaafeb2ab9',
            'dev_requirement' => false,
        ),
        'spatie/db-dumper' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/db-dumper',
            'aliases' => array(),
            'reference' => '1364325f3f3c5b7cdafd46bca5e9d422227a34d2',
            'dev_requirement' => false,
        ),
        'spatie/laravel-activitylog' => array(
            'pretty_version' => '4.0.0',
            'version' => '4.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/laravel-activitylog',
            'aliases' => array(),
            'reference' => 'f1e8e8ea2cb85945d5ac770e979b0381cc82da52',
            'dev_requirement' => false,
        ),
        'spatie/laravel-backup' => array(
            'pretty_version' => '7.6.0',
            'version' => '7.6.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/laravel-backup',
            'aliases' => array(),
            'reference' => '39dc00988cd28e7cd06237dae27bf463fa9420fd',
            'dev_requirement' => false,
        ),
        'spatie/laravel-multitenancy' => array(
            'pretty_version' => '2.1.1',
            'version' => '2.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/laravel-multitenancy',
            'aliases' => array(),
            'reference' => 'e7a30c546e1dacbeff7e89dd6f11dbdf3a36eadd',
            'dev_requirement' => false,
        ),
        'spatie/laravel-package-tools' => array(
            'pretty_version' => '1.9.0',
            'version' => '1.9.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/laravel-package-tools',
            'aliases' => array(),
            'reference' => 'cf4c4cec220575e2864c6082842d76822421f1b1',
            'dev_requirement' => false,
        ),
        'spatie/laravel-permission' => array(
            'pretty_version' => '4.2.0',
            'version' => '4.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/laravel-permission',
            'aliases' => array(),
            'reference' => 'a6e4122b65094baba7f98df153af0768ef910c85',
            'dev_requirement' => false,
        ),
        'spatie/laravel-ray' => array(
            'pretty_version' => '1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/laravel-ray',
            'aliases' => array(),
            'reference' => '2e49e83f3df25e4ef7a145cb0247d2038b8d3436',
            'dev_requirement' => false,
        ),
        'spatie/laravel-responsecache' => array(
            'pretty_version' => '7.1.0',
            'version' => '7.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/laravel-responsecache',
            'aliases' => array(),
            'reference' => '3bf314f2e6ed7644b9dc182817b48754c928008c',
            'dev_requirement' => false,
        ),
        'spatie/laravel-settings' => array(
            'pretty_version' => '2.1.8',
            'version' => '2.1.8.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/laravel-settings',
            'aliases' => array(),
            'reference' => '70d8391845590c72755609f3fbf249857d000828',
            'dev_requirement' => false,
        ),
        'spatie/laravel-signal-aware-command' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/laravel-signal-aware-command',
            'aliases' => array(),
            'reference' => '8c605808028943da9f6c0064d3fd16358526bcad',
            'dev_requirement' => false,
        ),
        'spatie/macroable' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/macroable',
            'aliases' => array(),
            'reference' => 'ec2c320f932e730607aff8052c44183cf3ecb072',
            'dev_requirement' => false,
        ),
        'spatie/ray' => array(
            'pretty_version' => '1.28.0',
            'version' => '1.28.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/ray',
            'aliases' => array(),
            'reference' => 'b800636fb022b93df53bd90fa52e5ed07221eb6a',
            'dev_requirement' => false,
        ),
        'spatie/temporary-directory' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/temporary-directory',
            'aliases' => array(),
            'reference' => '06fe0f10d068fdf145c9b2235030e568c913bb61',
            'dev_requirement' => false,
        ),
        'swiftmailer/swiftmailer' => array(
            'pretty_version' => 'v6.2.7',
            'version' => '6.2.7.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../swiftmailer/swiftmailer',
            'aliases' => array(),
            'reference' => '15f7faf8508e04471f666633addacf54c0ab5933',
            'dev_requirement' => false,
        ),
        'symfony/console' => array(
            'pretty_version' => 'v5.3.2',
            'version' => '5.3.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'reference' => '649730483885ff2ca99ca0560ef0e5f6b03f2ac1',
            'dev_requirement' => false,
        ),
        'symfony/css-selector' => array(
            'pretty_version' => 'v5.3.0',
            'version' => '5.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/css-selector',
            'aliases' => array(),
            'reference' => 'fcd0b29a7a0b1bb5bfbedc6231583d77fea04814',
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v2.5.0',
            'version' => '2.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'reference' => '6f981ee24cf69ee7ce9736146d1c57c2780598a8',
            'dev_requirement' => false,
        ),
        'symfony/error-handler' => array(
            'pretty_version' => 'v5.3.3',
            'version' => '5.3.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/error-handler',
            'aliases' => array(),
            'reference' => '43323e79c80719e8a4674e33484bca98270d223f',
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher' => array(
            'pretty_version' => 'v5.3.0',
            'version' => '5.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher',
            'aliases' => array(),
            'reference' => '67a5f354afa8e2f231081b3fa11a5912f933c3ce',
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-contracts' => array(
            'pretty_version' => 'v2.4.0',
            'version' => '2.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher-contracts',
            'aliases' => array(),
            'reference' => '69fee1ad2332a7cbab3aca13591953da9cdb7a11',
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.0',
            ),
        ),
        'symfony/filesystem' => array(
            'pretty_version' => 'v5.3.3',
            'version' => '5.3.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/filesystem',
            'aliases' => array(),
            'reference' => '19b71c8f313b411172dd5f470fd61f24466d79a9',
            'dev_requirement' => false,
        ),
        'symfony/finder' => array(
            'pretty_version' => 'v5.3.0',
            'version' => '5.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/finder',
            'aliases' => array(),
            'reference' => '0ae3f047bed4edff6fd35b26a9a6bfdc92c953c6',
            'dev_requirement' => false,
        ),
        'symfony/http-client-contracts' => array(
            'pretty_version' => 'v2.4.0',
            'version' => '2.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-client-contracts',
            'aliases' => array(),
            'reference' => '7e82f6084d7cae521a75ef2cb5c9457bbda785f4',
            'dev_requirement' => false,
        ),
        'symfony/http-foundation' => array(
            'pretty_version' => 'v5.3.3',
            'version' => '5.3.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-foundation',
            'aliases' => array(),
            'reference' => '0e45ab1574caa0460d9190871a8ce47539e40ccf',
            'dev_requirement' => false,
        ),
        'symfony/http-kernel' => array(
            'pretty_version' => 'v5.3.3',
            'version' => '5.3.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-kernel',
            'aliases' => array(),
            'reference' => '90ad9f4b21ddcb8ebe9faadfcca54929ad23f9f8',
            'dev_requirement' => false,
        ),
        'symfony/mime' => array(
            'pretty_version' => 'v5.3.2',
            'version' => '5.3.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/mime',
            'aliases' => array(),
            'reference' => '47dd7912152b82d0d4c8d9040dbc93d6232d472a',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'reference' => '46cd95797e9df938fdd2b03693b5fca5e64b01ce',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-iconv' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-iconv',
            'aliases' => array(),
            'reference' => '63b5bb7db83e5673936d6e3b8b3e022ff6474933',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-grapheme' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-grapheme',
            'aliases' => array(),
            'reference' => '24b72c6baa32c746a4d0840147c9715e42bb68ab',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-idn',
            'aliases' => array(),
            'reference' => '65bd267525e82759e7d8c4e8ceea44f398838e65',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'reference' => '8590a5f561694770bdcd3f9b5c69dde6945028e8',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.24.0',
            'version' => '1.24.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'reference' => '0abb51d2f102e00a4eefcf46ba7fec406d245825',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php72' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php72',
            'aliases' => array(),
            'reference' => '9a142215a36a3888e30d0a9eeea9766764e96976',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php73' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php73',
            'aliases' => array(),
            'reference' => 'fba8933c384d6476ab14fb7b8526e5287ca7e010',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'reference' => 'eca0bf41ed421bed1b57c4958bab16aa86b757d0',
            'dev_requirement' => false,
        ),
        'symfony/process' => array(
            'pretty_version' => 'v5.3.2',
            'version' => '5.3.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/process',
            'aliases' => array(),
            'reference' => '714b47f9196de61a196d86c4bad5f09201b307df',
            'dev_requirement' => false,
        ),
        'symfony/psr-http-message-bridge' => array(
            'pretty_version' => 'v2.1.0',
            'version' => '2.1.0.0',
            'type' => 'symfony-bridge',
            'install_path' => __DIR__ . '/../symfony/psr-http-message-bridge',
            'aliases' => array(),
            'reference' => '81db2d4ae86e9f0049828d9343a72b9523884e5d',
            'dev_requirement' => false,
        ),
        'symfony/routing' => array(
            'pretty_version' => 'v5.3.0',
            'version' => '5.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/routing',
            'aliases' => array(),
            'reference' => '368e81376a8e049c37cb80ae87dbfbf411279199',
            'dev_requirement' => false,
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => 'v2.4.0',
            'version' => '2.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(),
            'reference' => 'f040a30e04b57fbcc9c6cbcf4dbaa96bd318b9bb',
            'dev_requirement' => false,
        ),
        'symfony/stopwatch' => array(
            'pretty_version' => 'v5.3.0',
            'version' => '5.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/stopwatch',
            'aliases' => array(),
            'reference' => '313d02f59d6543311865007e5ff4ace05b35ee65',
            'dev_requirement' => false,
        ),
        'symfony/string' => array(
            'pretty_version' => 'v5.3.3',
            'version' => '5.3.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/string',
            'aliases' => array(),
            'reference' => 'bd53358e3eccec6a670b5f33ab680d8dbe1d4ae1',
            'dev_requirement' => false,
        ),
        'symfony/translation' => array(
            'pretty_version' => 'v5.3.3',
            'version' => '5.3.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation',
            'aliases' => array(),
            'reference' => '380b8c9e944d0e364b25f28e8e555241eb49c01c',
            'dev_requirement' => false,
        ),
        'symfony/translation-contracts' => array(
            'pretty_version' => 'v2.4.0',
            'version' => '2.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation-contracts',
            'aliases' => array(),
            'reference' => '95c812666f3e91db75385749fe219c5e494c7f95',
            'dev_requirement' => false,
        ),
        'symfony/translation-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.3',
            ),
        ),
        'symfony/var-dumper' => array(
            'pretty_version' => 'v5.3.3',
            'version' => '5.3.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-dumper',
            'aliases' => array(),
            'reference' => '46aa709affb9ad3355bd7a810f9662d71025c384',
            'dev_requirement' => false,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v5.3.3',
            'version' => '5.3.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'reference' => '485c83a2fb5893e2ff21bf4bfc7fdf48b4967229',
            'dev_requirement' => false,
        ),
        'theseer/tokenizer' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../theseer/tokenizer',
            'aliases' => array(),
            'reference' => '75a63c33a8577608444246075ea0af0d052e452a',
            'dev_requirement' => true,
        ),
        'tijsverkoyen/css-to-inline-styles' => array(
            'pretty_version' => '2.2.3',
            'version' => '2.2.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tijsverkoyen/css-to-inline-styles',
            'aliases' => array(),
            'reference' => 'b43b05cf43c1b6d849478965062b6ef73e223bb5',
            'dev_requirement' => false,
        ),
        'vlucas/phpdotenv' => array(
            'pretty_version' => 'v5.3.0',
            'version' => '5.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../vlucas/phpdotenv',
            'aliases' => array(),
            'reference' => 'b3eac5c7ac896e52deab4a99068e3f4ab12d9e56',
            'dev_requirement' => false,
        ),
        'voku/portable-ascii' => array(
            'pretty_version' => '1.5.6',
            'version' => '1.5.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../voku/portable-ascii',
            'aliases' => array(),
            'reference' => '80953678b19901e5165c56752d087fc11526017c',
            'dev_requirement' => false,
        ),
        'vyuldashev/xml-to-array' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../vyuldashev/xml-to-array',
            'aliases' => array(),
            'reference' => 'ae1713b167093716b8e8d56bfb318befac4a8c4b',
            'dev_requirement' => false,
        ),
        'webmozart/assert' => array(
            'pretty_version' => '1.10.0',
            'version' => '1.10.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webmozart/assert',
            'aliases' => array(),
            'reference' => '6964c76c7804814a842473e0c8fd15bab0f18e25',
            'dev_requirement' => false,
        ),
        'widmogrod/php-functional' => array(
            'pretty_version' => '6.0.0',
            'version' => '6.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../widmogrod/php-functional',
            'aliases' => array(),
            'reference' => 'a1a4edc7f135c4b9364afadcb23d91629255b06c',
            'dev_requirement' => false,
        ),
        'zbateson/mail-mime-parser' => array(
            'pretty_version' => '1.3.1',
            'version' => '1.3.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../zbateson/mail-mime-parser',
            'aliases' => array(),
            'reference' => '706964d904798b8c22d63f62f0ec5f5bc84e30d9',
            'dev_requirement' => false,
        ),
        'zbateson/mb-wrapper' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../zbateson/mb-wrapper',
            'aliases' => array(),
            'reference' => '721b3dfbf7ab75fee5ac60a542d7923ffe59ef6d',
            'dev_requirement' => false,
        ),
        'zbateson/stream-decorators' => array(
            'pretty_version' => '1.0.4',
            'version' => '1.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../zbateson/stream-decorators',
            'aliases' => array(),
            'reference' => '6f54738dfecc65e1d5bfb855035836748083a6dd',
            'dev_requirement' => false,
        ),
    ),
);
